--
--  ******* INICIO - TABELAS ********
--

CREATE TABLE TURMA (
    `CODIGO_TURMA` BIGINT(20) NOT NULL,
    `CODIGO_PROFESSOR_TURMA` BIGINT(20) NOT NULL,
    `DESCRICAO_TURMA` VARCHAR(255) NOT NULL,
    `DATA_INICIO_TURMA` DATETIME NOT NULL,
    `DATA_FIM_TURMA` DATETIME NOT NULL,
    `DATA_PREVISAO_EVENTO` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PAROQUIA (
    `CODIGO_PAROQUIA` BIGINT(20) NOT NULL,
    `DESRICAO_PAROQUIA` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PARQUIA_ALUNO (
    `CODIGO_ALUNO_PAROQUIA_ALUNO` BIGINT(20) NOT NULL,
    `CODIGO_PAROQUIA_PAROQUIA_ALUNO` BIGINT(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PAROQUIA_ENDERECO (
    `CODIGO_PAROQUIA_ENDERECO` BIGINT(20) NOT NULL,
    `CODIGO_PAROQUIA_PAROQUIA_ENDERECO` BIGINT(20) NOT NULL,
    `CODIGO_CIDADE_PAROQUIA_ENDERECO` BIGINT(20) NOT NULL,
    `RUA_PAROQUIA_ENDERECO` VARCHAR(255),
    `NUMERO_PAROQUIA_ENDERECO` VARCHAR(255),
    `BAIRRO_PAROQUIA_ENDERECO` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CIDADE (
    `CODIGO_CIDADE` BIGINT(20) NOT NULL,
    `DESCRICAO_CIDADE` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROFESSOR (
    `CODIGO_PROFESSOR` BIGINT(20) NOT NULL,
    `DESCRICAO_PROFESSOR` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROFESSOR_TELEFONE (
    `CODIGO_PROFESSOR_TELEFONE` BIGINT(20) NOT NULL,
    `CODIGO_PROFESSOR_PROFESSOR_TELEFONE` BIGINT(20) NOT NULL,
    `DDD_PROFESSOR_TELEFONE` VARCHAR(255) NOT NULL,
    `NUMERO_PROFESSOR_TELEFONE` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ALUNO (
    `CODIGO_ALUNO` BIGINT(20) NOT NULL,
    `NOME_ALUNO` VARCHAR(255) NOT NULL,
    `STATUS_ALUNO` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ALUNO_TELEFONE (
    `CODIGO_ALUNO_TELEFONE` BIGINT(20) NOT NULL,
    `CODIGO_ALUNO_ALUNO_TELEFONE` BIGINT(20) NOT NULL,
    `DDD_ALUNO_TELEFONE` VARCHAR(255) NOT NULL,
    `NUMERO_ALUNO_TELEFONE` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ALUNO_ENDERECO (
    `CODIGO_ALUNO_ENDERECO` BIGINT(20) NOT NULL,
    `CODIGO_ALUNO_ALUNO_ENDERECO` BIGINT(20) NOT NULL,
    `CODIGO_CIDADE_ALUNO_ENDERECO` BIGINT(20) NOT NULL,
    `RUA_ALUNO_ENDERECO` VARCHAR(255),
    `NUMERO_ALUNO_ENDERECO` VARCHAR(255),
    `BAIRRO_ALUNO_ENDERECO` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ALUNO_PRESENCA (
    `CODIGO_ALUNO_PRESENCA` BIGINT(20) NOT NULL,
    `CODIGO_ALUNO_ALUNO_PRESENCA` BIGINT(20) NOT NULL,
    `PRESENCA_ALUNO_PRESENCA` TINYINT(1) NOT NULL,
    `DATA_ALUNO_PRESENCA` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PAROQUIA_TELEFONE (
    `CODIGO_PAROQUIA_TELEFONE` BIGINT(20) NOT NULL,
    `CODIGO_PAROQUIA_PROFESSOR_TELEFONE` BIGINT(20) NOT NULL,
    `DDD_PAROQUIA_TELEFONE` VARCHAR(255) NOT NULL,
    `NUMERO_PAROQUIA_TELEFONE` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
--  ******* FIM - TABELAS ********
--


--
--  ******* INICIO - CHAVES PRIMÁRIAS ********
--

ALTER TABLE `TURMA`
  ADD PRIMARY KEY (`CODIGO_TURMA`);

ALTER TABLE `PAROQUIA`
  ADD PRIMARY KEY (`CODIGO_PAROQUIA`);

ALTER TABLE `ALUNO`
  ADD PRIMARY KEY (`CODIGO_ALUNO`);

ALTER TABLE `PAROQUIA_ENDERECO`
  ADD PRIMARY KEY (`CODIGO_PAROQUIA_ENDERECO`);

ALTER TABLE `CIDADE`
  ADD PRIMARY KEY (`CODIGO_CIDADE`);

ALTER TABLE `PROFESSOR`
  ADD PRIMARY KEY (`CODIGO_PROFESSOR`);

ALTER TABLE `PROFESSOR_TELEFONE`
  ADD PRIMARY KEY (`CODIGO_PROFESSOR_TELEFONE`);

ALTER TABLE `ALUNO_TELEFONE`
  ADD PRIMARY KEY (`CODIGO_ALUNO_TELEFONE`);

ALTER TABLE `ALUNO_ENDERECO`
  ADD PRIMARY KEY (`CODIGO_ALUNO_ENDERECO`);
  
ALTER TABLE `ALUNO_PRESENCA`
  ADD PRIMARY KEY (`CODIGO_ALUNO_PRESENCA`);

ALTER TABLE `PAROQUIA_TELEFONE`
  ADD PRIMARY KEY (`CODIGO_PAROQUIA_TELEFONE`);

--
--  ******* FIM - CHAVES PRIMÁRIAS ********
--

--
--  ******* AUTO INCREMENTO NAS - CHAVES PRIMÁRIAS ********
--

ALTER TABLE `TURMA`
  MODIFY `CODIGO_TURMA` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `PAROQUIA`
  MODIFY `CODIGO_PAROQUIA` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `ALUNO`
  MODIFY `CODIGO_ALUNO` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `PAROQUIA_ENDERECO`
  MODIFY `CODIGO_PAROQUIA_ENDERECO` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `CIDADE`
  MODIFY `CODIGO_CIDADE` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `PROFESSOR`
  MODIFY `CODIGO_PROFESSOR` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `PROFESSOR_TELEFONE`
  MODIFY `CODIGO_PROFESSOR_TELEFONE` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `ALUNO_TELEFONE`
  MODIFY `CODIGO_ALUNO_TELEFONE` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `ALUNO_ENDERECO`
  MODIFY `CODIGO_ALUNO_ENDERECO` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `ALUNO_PRESENCA`
  MODIFY `CODIGO_ALUNO_PRESENCA` BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `PAROQUIA_TELEFONE`
  MODIFY `CODIGO_PAROQUIA_TELEFONE` BIGINT(20) NOT NULL AUTO_INCREMENT;

--
--  ******* INICIO - CHAVES ESTRANGEIRAS ********
--

ALTER TABLE `TURMA`
  ADD FOREIGN KEY (`CODIGO_PROFESSOR_TURMA`) REFERENCES `PROFESSOR` (`CODIGO_PROFESSOR`);

ALTER TABLE `PARQUIA_ALUNO`
  ADD FOREIGN KEY (`CODIGO_ALUNO_PAROQUIA_ALUNO`) REFERENCES `ALUNO` (`CODIGO_ALUNO`);

ALTER TABLE `PARQUIA_ALUNO`
  ADD FOREIGN KEY (`CODIGO_PAROQUIA_PAROQUIA_ALUNO`) REFERENCES `PAROQUIA` (`CODIGO_PAROQUIA`);

ALTER TABLE `ALUNO_PRESENCA`
  ADD FOREIGN KEY (`CODIGO_ALUNO_ALUNO_PRESENCA`) REFERENCES `ALUNO` (`CODIGO_ALUNO`);

ALTER TABLE `PAROQUIA_ENDERECO`
  ADD FOREIGN KEY (`CODIGO_PAROQUIA_PAROQUIA_ENDERECO`) REFERENCES `PAROQUIA` (`CODIGO_PAROQUIA`);

ALTER TABLE `PAROQUIA_ENDERECO`
  ADD FOREIGN KEY (`CODIGO_CIDADE_PAROQUIA_ENDERECO`) REFERENCES `CIDADE` (`CODIGO_CIDADE`);
  
ALTER TABLE `PROFESSOR_TELEFONE`
  ADD FOREIGN KEY (`CODIGO_PROFESSOR_PROFESSOR_TELEFONE`) REFERENCES `PROFESSOR` (`CODIGO_PROFESSOR`);
  
ALTER TABLE `ALUNO_TELEFONE`
  ADD FOREIGN KEY (`CODIGO_ALUNO_ALUNO_TELEFONE`) REFERENCES `ALUNO` (`CODIGO_ALUNO`);

ALTER TABLE `ALUNO_ENDERECO`
  ADD FOREIGN KEY (`CODIGO_ALUNO_ALUNO_ENDERECO`) REFERENCES `ALUNO` (`CODIGO_ALUNO`);
  
ALTER TABLE `ALUNO_ENDERECO`
  ADD FOREIGN KEY (`CODIGO_CIDADE_ALUNO_ENDERECO`) REFERENCES `CIDADE` (`CODIGO_CIDADE`);

--
--  ******* FIM - CHAVES ESTRANGEIRAS ********
--